const COMMANDS = {
  BALANCE: 'BALANCE',
  CHECK_IN: 'CHECK_IN',
  PRINT_SUMMARY: 'PRINT_SUMMARY',
}

const FARES = {
  ADULT: 200,
  SENIOR_CITIZEN: 100,
  KID: 50,
}

const SERVICE_FEE_RATE = 0.02
const RETURN_FARE_DIVISOR = 2

const STATIONS = {
  CENTRAL: 'CENTRAL',
  AIRPORT: 'AIRPORT',
}

const OUTPUT_LABELS = {
  TOTAL_COLLECTION: 'TOTAL_COLLECTION',
  PASSENGER_TYPE_SUMMARY: 'PASSENGER_TYPE_SUMMARY',
}

const PASSENGER_TYPES = {
  ADULT: 'ADULT',
  SENIOR_CITIZEN: 'SENIOR_CITIZEN',
  KID: 'KID',
}

const ERROR_MESSAGES = {
  CARD_NOT_REGISTERED: 'CARD_NOT_REGISTERED {cardId}',
  STATION_NOT_FOUND: 'STATION_NOT_FOUND {station}',
}

module.exports = {
  COMMANDS,
  FARES,
  SERVICE_FEE_RATE,
  RETURN_FARE_DIVISOR,
  STATIONS,
  OUTPUT_LABELS,
  ERROR_MESSAGES,
  PASSENGER_TYPES,
}
